name: CI

on: [push, pull_request]

env:
  # See https://github.com/jruby/jruby/issues/5509
  JAVA_OPTS: "--add-opens java.xml/com.sun.org.apache.xerces.internal.impl=org.jruby.dist"

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.7, 3.0, 3.1, 3.2, 3.3, 3.4, jruby, truffleruby, "truffleruby+graalvm"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install --without documentation
    - name: Run tests
      run: bundle exec rake
